spring:
   datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://10.1.11.110:3310/baojia_bike?&zeroDateTimeBehavior=convertToNull&useSSL=false
        username: baojia_xm
        password: DgisNKhg
        druid:
            initial-size: 100
            max-active: 10000
            min-idle: 100
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 200
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: true
            test-on-return: false
            filter:
                stat:
                    logSlowSql: true
                    slowSqlMillis: 1
                    mergeSql: false
                wall:
                    config:
                        multiStatementAllow: true
   data:
      mongodb:
        #uri: mongodb://192.168.3.173:27017
        uri: mongodb://10.1.11.110:27017
        database: Balance
   redis:
      host: 10.1.11.110
      database: 0
      password: 6390
      port: 6390
      timeout: 1000
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
      cluster:
        nodes: 10.1.11.110:26379 #j集群节点
      sentinel:
        nodes: 10.1.11.110:26379  #哨兵节点
        master: testmaster
   kafka:
     bootstrap-servers:  10.1.11.147:9092
     producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
        batch-size: 65536
        buffer-memory: 524288
     consumer:
       group-id: 0
       enable-auto-commit: true
       auto-offset-reset: earliest
       key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
       value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#   activemq:
#     broker-url:  tcp://47.94.232.109:61616
#     user:
#     password:
#     in-memory: false
#     pool:
#       enabled: true
logging:
  config: classpath:logback-dev.xml
#eureka:
#  client:
#    register-with-eureka: false  #表示是否注册Eureka服务器,因为自身作为服务注册中心，所以为false
#    fetch-registry: false #是否从eureka上获取注册信息，同上